# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - master
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - master
    - release/*.*
  paths:
    include:
    - '*'
    - docs/manpages/*
    exclude:
    - eng/Version.Details.xml
    - docs/*
    - CODE-OF-CONDUCT.md
    - CONTRIBUTING.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common/variables.yml

jobs:
#
# Checkout repository
#
- template: /eng/pipelines/common/checkout-job.yml
  parameters:
    paths:
    - subset: coreclr
      include:
      - src/libraries/System.Private.CoreLib/*
      - src/libraries/Native/Unix/System.Globalization.Native/*
      - src/libraries/Native/Unix/Common/*
      exclude:
      - eng/Version.Details.xml
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/mono/*
      - src/libraries/*
      - eng/pipelines/installer/*
      - eng/pipelines/mono/*
      - eng/pipelines/libraries/*
    - subset: mono
      include:
      - src/libraries/System.Private.CoreLib/*
      exclude:
      - eng/Version.Details.xml
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/coreclr/*
      - src/libraries/*
      - eng/pipelines/installer/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/libraries/*
    - subset: libraries
      exclude:
      - eng/Version.Details.xml
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/installer/*
      - src/mono/*
      - src/coreclr/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/mono/*
      - eng/pipelines/installer/*
    - subset: installer
      include:
      - docs/manpages/*
      exclude:
      - eng/Version.Details.xml
      - '*.md'
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT
      - docs/*
      - src/coreclr/*
      - src/mono/*
      - src/libraries/*
      - eng/pipelines/coreclr/*
      - eng/pipelines/mono/*
      - eng/pipelines/libraries/*

#
# Build Mono release
# Only when libraries or mono changed
#
- template: /eng/pipelines/common/platform-matrix.yml
  parameters:
    jobTemplate: /eng/pipelines/mono/templates/build-job.yml
    runtimeFlavor: mono
    buildConfig: release
    platforms:
    - iOS_arm
    jobParameters:
      condition: >-
        or(
          eq(dependencies.checkout.outputs['SetPathVars_libraries.containsChange'], true),
          eq(dependencies.checkout.outputs['SetPathVars_mono.containsChange'], true),
          eq(variables['isFullMatrix'], true))


- template: /eng/pipelines/installer/installer-matrix.yml
  parameters:
    buildConfig: ${{ variables.debugOnPrReleaseOnRolling }}
    runtimeFlavor: mono
    platforms:
    - iOS_arm # https://github.com/dotnet/runtime/issues/34465
    jobParameters:
      liveRuntimeBuildConfig: release
      liveLibrariesBuildConfig: Release
